# Change these first
owner: bishal520 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: gpkmc college
    url: https://www.gpkmc.edu.np
  - name: bishal
    url: https://www.bishalluitel.com.np
   - name: pashupatitimes
    url: https://www.pashupatitimes.com
  
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.bishalluitel.com.np
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for bishal 
  introTitle: "**Upptime** status page for bishal."
  introMessage: This is status page powered by bishal 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  i18n:
  footer: This page is [open source]($REPO), powered by [bishal]

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
