# Change these first
owner: bishal520 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: gpkmc college
    url: https://www.gpkmc.edu.np
  - name: bishal
    url: https://www.bishalluitel.com.np
  - name: pashupatitimes
    url: https://www.pashupatitimes.com
  - name: fcube
    url: https://www.fcubecinemas.com/
  - name: project
    url: https://project.bishalluitel.com.np/
  - name: Minecraft np azerith
    check: "tcp-ping"
    url: as.azerithmc.com
    port: 25565
  
status-website:
  theme: dark
  cname: uptime.bishalluitel.com.np
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for bishal 
  introTitle: "**Upptime** status page for bishal."
  introMessage: This is status page powered by bishal 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  i18n:
  footer: This page is [open source]($REPO), powered by [bishal]
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
